################################################################
volumes:
    forntvol:
    backvol:
################################################################
networks:
    # this will create a default bridge network 
    frontend:
    # this will create a manually ip bridge network 
    backend:
        ipam:
            driver: default
            config: 
                - subnet: 192.168.10.0/24


    # this will create a manually macvlan  network 
    macvlan_ip:
          driver: macvlan          # driver type
          driver_opts: 
                parent: eth0         #net port number
          ipam:
              config:
                  - subnet: 192.168.5.0/24
                  - gateway: 192.168.5.1
          
################################################################
services:
# this is container1 create using Dockerfile
  web1:                           # container name
    build: .                      # build image using Docker file
    ports:                        # port assign to this container while running
        - 30020:80      # hostport : container port
        - 30021:8080    # hostport : container port
    networks:                     #  Network assign to this container
        - frontend
    ########### container dependent container to Database ################
    depends_on:
        - db
    ######################################################################
        
# this is container2 create using Dockerfile
  db:
    image: mysql:5.6
    enviroment:
        MYSQL_ROOT_PASSWORD=redhat
        MYSQL_USER=abhi
        MYSQL_PASSWORD=1234ab
    volumes:
        - backend:/var/lib/mysql
    networks:
        - backend
    

# this is container3 create 
  wordpress:
    image: wordpress
    ports:
      - 
    enviroment:
        WORDPRESS_DB_HOST=db
        WORDPRESS_DB_USER=abhi
        WORDPRESS_DB_PASSWORD=1234ab
    volumes:
        - forntvol:/var/www/html
    networks:
        - macvlan_ip
        - backend
    
    ########### container dependent container to Database ################
    depends_on:
        - web1
    ######################################################################
    
    
